server:
  port: 8080

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

spring:
  application:
    name: app
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: My.SQLDialect
  output:
    ansi:
      enabled: always

sentry:
  dsn: https://7028c96741d06defc3c0c3cea471765e@o4507837344251904.ingest.us.sentry.io/4507837353230336
  tracesSampleRate: 1.0
