server:
  port: 8080

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

spring:
  application:
    name: app
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: My.SQLDialect
  output:
    ansi:
      enabled: always